### ISSUE TITLE
Not listed in Package Control

### ISSUE THREAD

**Issue by aMoniker** [waynemoore/sublime-gherkin-formatter#16]
Just installed directly via git, and it works well. Thanks for the useful plugin!

I couldn't find it in Package Control though. Am I missing something there?

**Comment by waynemoore** [comment]
Glad you find it useful :smile: 

It should be there in Package Control, if you fire up the Install Package dialog and start typing "Gherkin" you should see it pretty quickly.  I double checked both ST2 & ST3.

![screen shot 2014-10-07 at 08 18 55](https://cloud.githubusercontent.com/assets/96995/4538594/55439042-4df2-11e4-8452-6a563d20d1f2.png)

Let me know if you still have trouble and let's see if we can get to the bottom if it.

**Comment by aMoniker** [comment]
You're right. It was already installed; I just hadn't used it until now. :laughing:

Sorry for the trouble, and thanks for checking!

**Comment by waynemoore** [comment]
lol, no worries.
