### ISSUE TITLE
fyi: Clone for Synw

### ISSUE THREAD

**Issue by Alexey-T** [waynemoore/sublime-gherkin-formatter#18]
hi Wayne. If u don't mind i made a clone http://synwrite.sourceforge.net/forums/viewtopic.php?f=19&t=1218

**Comment by waynemoore** [comment]
Hi @Alexey-T :smile: 

Yes of course, no problem -- that's exactly why I use a liberal license.  I would however appreciate that you submit any bugfixes back upstream to me.

My parser is quite crude -- but it get's the job done.  I'm considering using https://github.com/clarete/gherkin but it currently doesn't include indents in the parsed output.  I will consider submitting a patch in the future, then it'll probably be better for us both to use that.
