### ISSUE TITLE
Change format key to match Text Mate

### ISSUE THREAD

**Issue by waynemoore** [waynemoore/sublime-gherkin-formatter#4]
After a 15min berating by @artismarti and @FreakyDazio on campfire I have been beaten into submission...

Change the key to trigger table formatting to match Text Mate's: `cmd+shift+|`

**Comment by dcoxall** [comment]
Who the hell uses `|`!?

Okay that will do I suppose :smile:

**Comment by artismarti** [comment]
About freaking time @waynemoore 

I mean THANK YOU.

**Comment by waynemoore** [comment]
What were you expecting? Don't make me come over there and ask :wink:

**Comment by artismarti** [comment]
Can it make me a sandwich? Vegan, ofcourse.

**Comment by waynemoore** [comment]
sudo make yourself a sandwich :wink:

**Comment by artismarti** [comment]
Useless software. 1 star.
