### ISSUE TITLE
Leave the caret where it is

### ISSUE THREAD

**Issue by Simbul** [waynemoore/sublime-gherkin-formatter#7]
I've noticed a minor annoyance: when running the script (in my case using the keyboard shortcut) sometimes vertical scroll and caret position are changed.
It looks like the caret ends up at the bottom of the document, but vertical scroll brings the view back to the top.

**Comment by waynemoore** [comment]
> Leave the caret where it is

Is that some obscure vegetarian joke?

:wink: I'll have a look, thanks for reporting.
