### ISSUE TITLE
Doesn't work in Sublime Text 2 v2.0.0 build 2221

### ISSUE THREAD

**Issue by wzup** [waynemoore/sublime-gherkin-formatter#8]
I had to upgrade ST2 (ST2 just forced everyone to do it). After that I installed the `sublime-gherkin-formatter` using Package Control. Now I have a directory `\Gherkin (Cucumber) Formatter` in my `\Sublime Text 2\Packages` dir. The full path looks like this:

```
C:\Documents and Settings\User\Application Data\Sublime Text 2\Packages\Gherkin (Cucumber) Formatter
```

So all has to work, but there is no Gherkin option in syntax menu `View > Syntax`. The folder with `\Gherkin (Cucumber) Formatter` exists in  `\Sublime Text 2\Packages` but the option in syntax is absent.]

Is it a bug with new ST2? How to enable the syntax?

**Comment by wzup** [comment]
Oops, I confused packages.
And it is good, I accidentally found your great package. And it works like a charm. There is no issues with your package.

Syntax highlighter is called `Cucumber` and is available from Package Control.

**Comment by waynemoore** [comment]
heh, no worries :wink:
